### ISSUE TITLE
Markdown proofer

### ISSUE THREAD

**Issue by agitter** [greenelab/manubot-rootstock#126] opened 2018-06-21 18:34 UTC
This [CircleCI blog](https://circleci.com/blog/markdown-proofer/) describes [Markdown Proofer](https://github.com/felicianotech/md-proofer) for validating YAML blocks in Markdown files.  It is written in Go, which we could get from [conda](https://anaconda.org/conda-forge/go), but it may not cleanly integrate into our test environment.  I'm also uncertain whether it could be applied directly to YAML files like `metadata.yaml`.

Nevertheless I thought it was worth monitoring.

**Comment by dhimmel** [comment] 2018-06-21 18:40
I am not sure what problem you are trying to solve.

Linting just YAML in code blocks in manuscripts seems arbitrary. Why not lint other languages then as well?

If instead the issue is making sure `metadata.yaml` is a valid YAML file and abides by a predefined schema, then I'd suggest using something like [pykwalify](https://github.com/Grokzen/pykwalify), which let's you define YAML schema which YAML files are validated against. This is what we've done for [`transpose-publishing/policies-database`](https://github.com/transpose-publishing/policies-database/tree/ce5502ec979f973e29767cf152338e9d6517ce5e). I could see some utility here, especially if we see common configurations of `metadata.yaml`. However, I'm not sure if we currently have a sufficient justification for the added complexity of schema validation.

**Comment by agitter** [comment] 2018-06-21 18:43
The latter is what I am more interested in, linting `metadata.yaml`.  This particular Markdown Proofer doesn't currently offer any advantages over that.

Feel free to close this.

**Comment by dhimmel** [comment] 2018-06-21 18:44
Okay let's close this, but others feel free to comment if linting and schema validation of `metadata.yaml` would be helpful and we'll reopen.

**Closed by dhimmel** 2018-06-21 18:44 UTC
