### ISSUE TITLE
macOS PDF build issues: long arguments not accepted & missing fonts in PDF

### ISSUE THREAD

**Issue by adebali** [greenelab/manubot-rootstock#120] opened 2018-03-27 23:55 UTC
`sh build/build.sh` fails on MAC OS as the following:

`ln --symbolic` and `rm --recursive` do not work. When I changed them to `ln -s` and `rm -r`, respectively, they are fine.

However, then it complains about `pango`. I manually installed it using homebrew and `pango` was not an issue anymore.

Then the build was completed with no errors but warnings:

```
WARNING: Ignored `-ms-text-size-adjust: 100%` at 78:5, unknown property.
WARNING: Ignored `-webkit-text-size-adjust: 100%` at 79:5, unknown property.
WARNING: Ignored `-moz-box-sizing: content-box` at 204:5, unknown property.
WARNING: Ignored `-webkit-appearance: button` at 379:5, unknown property.
WARNING: Ignored `cursor: pointer` at 380:5, the property does not apply for the print media.
WARNING: Ignored `cursor: default` at 389:5, the property does not apply for the print media.
WARNING: Ignored `-webkit-appearance: textfield` at 410:5, unknown property.
WARNING: Ignored `-moz-box-sizing: content-box` at 411:5, unknown property.
WARNING: Ignored `-webkit-box-sizing: content-box` at 412:5, unknown property.
WARNING: Ignored `-webkit-appearance: none` at 423:5, unknown property.
WARNING: Invalid or unsupported selector 'button::-moz-focus-inner,
input::-moz-focus-inner ', Unknown pseudo-element: -moz-focus-inner
WARNING: Invalid or unsupported selector '*:not("#mkdbuttons") ', (<FunctionBlock not( … )>, ':not() only accepts a simple selector')
WARNING: Ignored `-webkit-font-smoothing: subpixel-antialiased` at 486:5, unknown property.
WARNING: Ignored `-moz-border-radius: 3px` at 491:5, unknown property.
WARNING: Ignored `-webkit-border-radius: 3px
` at 492:5, unknown property.
WARNING: Ignored `-webkit-font-smoothing: subpixel-antialiased` at 528:5, unknown property.
WARNING: Ignored `cursor: text
` at 529:5, the property does not apply for the print media.
WARNING: Ignored `word-break: break-all` at 733:5, unknown property.
WARNING: Ignored `word-break: break-word` at 734:5, unknown property.
WARNING: Ignored `-webkit-hyphens: auto` at 735:5, unknown property.
WARNING: Ignored `-moz-hyphens: auto` at 736:5, unknown property.
```
And generated PDF has squares only. 

Do you have any idea on why this might be happening?

**Comment by dhimmel** [comment] 2018-03-28 02:04
Interesting regarding pango. It looks like we add pango to `environment.yml` so it gets intsalled [using conda](https://anaconda.org/conda-forge/pango) for macOS and linux.

Good to know about the long arguments not working on macOS (which OS version BTW)?

Those warnings are from WeasyPrint and are not a problem (they are always there).

> And generated PDF has squares only.

Not sure what you mean? The PDF is all garbled? Can you upload it to this issue? Would also be interested in whether the linux generated PDF from Travis has the issue or is okay.

**Comment by vsmalladi** [comment] 2018-03-28 02:44
I can confirm that on MacOS 10.11.6  the long arguments do not work.

**Comment by adebali** [comment] 2018-03-28 02:48
> (which OS version BTW)?

MacOS 10.13.3

> Can you upload it to this issue?

![image](https://user-images.githubusercontent.com/3449123/38005912-ed54d23c-3210-11e8-8a75-def4a31b9dfa.png)

> Would also be interested in whether the linux generated PDF from Travis has the issue or is okay.

Travis is ok.

**Comment by dhimmel** [comment] 2018-03-28 14:03
Regarding pango, the Travis Linux builds have the following warning ([example build](https://travis-ci.org/greenelab/manubot-rootstock/jobs/346527933#L1847)):

```
/home/travis/miniconda/envs/manubot/lib/python3.6/site-packages/weasyprint/fonts.py:43: UserWarning: @font-face support needs Pango >= 1.38
  warnings.warn('@font-face support needs Pango >= 1.38')
```

I haven't noticed any issues with font-faces in the output PDF, so we haven't added pango to the environment. @adebali were you having the issues with the squares prior to installing pango with brew?

Could you drag and drop the PDF into a GitHub comment below (GitHub should automatically upload it). This will help us diagnose whether the issue is with:

+ your PDF viewer
+ WeasyPrint and how it generates the PDF

Also if not sensitive, can you link to the repository where you're having these issues?

I'll get to fixing the shell commands macOS compatibility.

**Comment by adebali** [comment] 2018-03-28 17:11
> @adebali were you having the issues with the squares prior to installing pango with brew?

It was not possible to run `build.sh` before installing pango with brew.

[manuscript.pdf](https://github.com/greenelab/manubot-rootstock/files/1856951/manuscript.pdf)

**Comment by agitter** [comment] 2018-03-28 17:27
I also see the squares in `manuscript.pdf` in my PDF viewers.

**Comment by dhimmel** [comment] 2018-03-28 18:34
> I also see the squares in manuscript.pdf in my PDF viewers.

Me too. It's showing up as rectangles on Linux.

Tagging @liZe who has helped me with a WeasyPrint issue before (thanks!).  @liZe do you have any idea why the PDF @adebali is generating on macOS using WeasyPrint (called through Pandoc) shows all characters as rectangles? Are there any common issues that would cause this weird outcome?

**Comment by liZe** [comment] 2018-03-28 20:22
> Are there any common issues that would cause this weird outcome?

Yes!

With recent versions of WeasyPrint, we use fontconfig to find available fonts on the system. fontconfig needs to have a list of installed fonts, and this list can be updated using a tool called `fc-cache`. `fc-cache` is usually called when fontconfig is installed with homebrew, but for some reason the font cache may be empty for you. Try to call `fc-cache -frv` (that's what's called by fontconfig's package when installed), it should fix your problem.

**Comment by adebali** [comment] 2018-03-28 20:35
I followed the instruction and called `fc-cache -frv` then I did `sh build/build.sh`. I am still getting the same pdf. 

btw, @dhimmel the repo is here: https://github.com/adebali/manutry

**Comment by liZe** [comment] 2018-03-28 20:54
There's no font included in the PDF file, that's why you get these squares. If you use Pango < 1.38, you can try to either remove `@font-face` rules or force a `font-family` and see if it helps.

**Comment by rgieseke** [comment] 2018-04-04 09:14
I have a similar problem on OS X 10.11 (Linux works fine)

```
ImportError: dlopen(/Users/robert/.local/miniconda3/envs/manubot/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-darwin.so, 2): Symbol not found: _clock_gettime
  Referenced from: /Users/robert/.local/miniconda3/envs/manubot/lib/python3.6/site-packages/PIL/.dylibs/liblzma.5.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
```
I guess this is due to the earlier OS version, maybe related to this? https://stackoverflow.com/questions/2418157/ubuntu-linux-c-error-undefined-reference-to-clock-gettime-and-clock-settim

Anyway, a BUILD_PDF version like BUILD_DOCX would probably be helpful - I don't need the PDF for local development.

**Comment by dhimmel** [comment] 2018-04-04 21:37
> I have a similar problem on OS X 10.11 (Linux works fine)

I'm not sure whether it's similar. Are you saying the error happens at the PDF build stage? Does it result in the blank boxes or does it cause the build.sh script to fail and exit?

Not sure whose responsibility the `Symbol not found: _clock_gettime` error is. Refs https://github.com/pocoproject/poco/issues/1453. However, it makes me more convinced that Docker is the right solution here. But I need to think exactly how we want to manage and distribute the Manubot environment and whether Docker would make the environment more difficult to customize.

**Comment by rgieseke** [comment] 2018-04-05 09:15
> I'm not sure whether it's similar.

Yes, sorry I meant similar as in "also on Mac" ... the `--symbolic` problem was how I found this.

**Comment by dhimmel** [comment] 2018-11-08 18:56
I am going to close this issue because discussion has become too diffuse. To summarize, the issues that have been discussed are:

1. shell commands with long arguments that aren't supported on macOS. This was fixed in https://github.com/greenelab/manubot-rootstock/pull/123
2. generated PDFs that are missing fonts, due possibly to old versions of pango and/or due to the lack of fonts getting embedded in the PDF.
3. An issue with `Symbol not found: _clock_gettime`

I don't think 2 or 3 have been solved, but they may have been with updates. If you're still getting them, please open a new issue so we can keep things focused.

**Closed by dhimmel** 2018-11-08 18:56 UTC
